### PR TITLE
[CHORE] Update project setup

### PR DESCRIPTION
**Pull request by Modafi**
### What is the PR type?
- [ ] : feature
- [ ] : refactor
- [ ] : bug
- [ ] : documentation
- [x] : chore
- [ ] : displace
- [ ] : etc

### What does this PR do?

- Update application.yml
- Update gitignore
- Add dependency
    - JWT
    - Validated
- Add @PropertySource for env variables

### CODE REVIEW

**Comment by ruh0n** [comment]
너무 좋아요 굿굿 👍

**Comment by gloz0315** [comment]
너무 좋아요 👍

**Review by ruh0n — APPROVED** [review]

**Comment by devJWL** [comment]
좋습니다.

**Comment by devJWL** [comment]
LGTM

**Review by devJWL — APPROVED** [review]
LGTM

**Review by gloz0315 — APPROVED** [review]
LGTM

**Pull request merged**
